version: '2'
services:
  art-mysql:
    image: mysql:5
    volumes:
     - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: art
      MYSQL_ROOT_PASSWORD: root
    expose:
    - "3306"
